version: '3.9'
services:
  teeception-agent:
    restart: always
    image: ghcr.io/nethermindeth/teeception/agent:latest
    volumes:
      - /var/run/tappd.sock:/var/run/tappd.sock
      - tee:/app/storage
    ports:
      - "3000:3000"
      - "8080:8080"
    environment:
      X_USERNAME: ${X_USERNAME}
      X_PASSWORD: ${X_PASSWORD}
      X_CONSUMER_KEY: ${X_CONSUMER_KEY}
      X_CONSUMER_SECRET: ${X_CONSUMER_SECRET}
      X_CLIENT_MODE: ${X_CLIENT_MODE}
      AGENT_TWITTER_CLIENT_PORT: ${AGENT_TWITTER_CLIENT_PORT}
      AGENT_TWITTER_CLIENT_2FA_SECRET: ${AGENT_TWITTER_CLIENT_2FA_SECRET}
      PROTONMAIL_EMAIL: ${PROTONMAIL_EMAIL}
      PROTONMAIL_PASSWORD: ${PROTONMAIL_PASSWORD}
      STARKNET_RPC_URLS: ${STARKNET_RPC_URLS}
      CONTRACT_ADDRESS: ${CONTRACT_ADDRESS}
      CONTRACT_DEPLOYMENT_BLOCK: ${CONTRACT_DEPLOYMENT_BLOCK}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      X_LOGIN_SERVER_IP: ${X_LOGIN_SERVER_IP}
      X_LOGIN_SERVER_PORT: ${X_LOGIN_SERVER_PORT}
      SECURE_FILE: ${SECURE_FILE}
      DSTACK_TAPPD_ENDPOINT: ${DSTACK_TAPPD_ENDPOINT}
      UNENCUMBER_ENCRYPTION_KEY: ${UNENCUMBER_ENCRYPTION_KEY}
      DISABLE_ENCUMBERING: ${DISABLE_ENCUMBERING}
      DEBUG_PLAIN_SETUP: ${DEBUG_PLAIN_SETUP}
      DEBUG_SHOW_SETUP: ${DEBUG_SHOW_SETUP}
      DEBUG_SHOW_PASSWORD: ${DEBUG_SHOW_PASSWORD}
      DEBUG_DISABLE_REPLIES: ${DEBUG_DISABLE_REPLIES}
      DEBUG_DISABLE_TWEET_VALIDATION: ${DEBUG_DISABLE_TWEET_VALIDATION}
      DEBUG_DISABLE_CONSUMPTION: ${DEBUG_DISABLE_CONSUMPTION}
      DEBUG_DISABLE_WAITING_FOR_DEPLOYMENT: ${DEBUG_DISABLE_WAITING_FOR_DEPLOYMENT}
volumes:
  tee:
